global:
  evaluation_interval: 1s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

rule_files:
- 'rules/*.yaml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "127.0.0.1:9093"

